name: Testing zero to prod

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master


jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: install components
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy


      - name: install cargo components
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-audit cargo-tarpaulin -v

      - name: run linting
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

      - name: run check
        uses: actions-rs/cargo@v1
        with:
          command: check

      - name: run audit
        uses: actions-rs/cargo@v1
        with:
          command: audit

      - name: run code coverage
        uses: actions-rs/cargo@v1
        with:
          command: tarpaulin
          args: --coveralls ${{ secrets.COVERALLS_TOKEN }}

      - name: run tests
        uses: actions-rs/cargo@v1
        with:
          command: test

